# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 468eab9c601e7d545b6e487d79c576076383656dbd5c2fb86d9df2ee98338e987f516bea39404f517a6b2a08204d46093e2dbc331dde4e52ac68a1fc78fc1df8

test:
  secret_key_base: 5d03c20e4ce6e95d08a95649342a3b7696098b006bca5cf606d027ba18e4a278d15f4bb65e29e5b36afe66c2368d30c61554dec5a348520206f91807a23bedc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
